language: node_js
node_js:
  - 10
  - 8
  - 6
branches:
  only:
    - master
    - /^v[0-9]/
script:
  - nyc npm test
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: XExIdlOQVyEwN5J4j5DiC3ftDMthFwJr9PGi4Ko5QFLSG6tVzMbxe1OLnAVS7Oxx8hv7urqZPS7Ld2UgCQ3IDp1uqAjegqqOkEZ1ILD24jZ8ZbUtvqIsqeSu3sl2pr5iL8pxVyUUrIClBrInKZhWsDxUv6VeUBQ+lyqXSiPu3W429IPLS6KZuYQI1vdxn1hDc+3kn6vhRf+Oga902zVNXfcSGkB9Y27xknSFbj7ybh5+NFaDXuvn17X56BJl8zPNplxSL5G2qVCmpv3Q/+HNTU5sygV9/7eVYywQjgwyNWzx0k4TIGNw3oitnjiuN+G+0kB/b1HesITMrpZDAg8A+G6rTHLYGMyfVA2640qoomr05nyaDF3kaZ2k/qnyhTcD7Gxw+VEMbwBbLXoGx8JCPh+ojz14eN8s3wkstnaLq8SkSnb8xF8aykdc/jiPxlN3eI2aTiQd3XDbdKW1UtYTHv5LZ757OpnMO0JtWQuWL6DPH8dosm84DnjT+bjaQqIalQ5YRMc2+ZEQPQ7m5G6TUUjvWaG8XczPQ6u3mwlb6oCWSmg8SgJXddEieT+zddphyQbLoP93Ah187B8z8gwsp78c6/E8bNF15fjXX/nW7IW3X32sYZNZ2gUI28nSwKKL/QNCdhahH7ALyfyH8VTzdpccpm2mRl9CjXThW7fHsCE=
  on:
    tags: true
    node: 10
