name: CI

on:
  push:
    branches:
    - master
    tags:
    - v*.*.*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run test-coverage
    - run: npm run report-coverage -- --check-coverage --lines 100
    - uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage
    - run: npm publish
      if: startsWith(github.ref, 'refs/tags/')
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
